# Generated by Django 3.2.15 on 2025-04-06 13:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='контактный телефон'),
        ),
    ]
