# Generated by Django 4.2.20 on 2025-05-02 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_products',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='количество'),
        ),
    ]
