# Generated by Django 4.2.20 on 2025-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('IP', 'Принят в обработку'), ('IK', 'Передан на приготовление'), ('KP', 'Готовиться'), ('DTC', 'Передан курьеру'), ('IT', 'В пути'), ('DE', 'Доставлен'), ('CL', 'Закрыт')], db_index=True, default='CR', max_length=25, verbose_name='Статус'),
        ),
    ]
