# Generated by Django 4.2.20 on 2025-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CA', 'Наличными'), ('TR', 'Электронно')], db_index=True, default='TR', max_length=25, verbose_name='Способ оплаты'),
        ),
    ]
