# Generated by Django 3.2.15 on 2025-06-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20250603_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registreted_at',
            new_name='registered_at',
        ),
    ]
